[tool.poetry]
name = "airbyte-deployment"
version = "0.1.0"
description = ""
authors = ["donatien konan <donatien.konan.pro@gmail.com>"]
package-mode = false
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
pendulum = "^3.0.0"
pytest = "^8.3.4"
apache-airflow = {version = "^2.3.0", extras = ["postgres", "airbyte"]}
ipython = "^8.4.0"
pyarrow = "^8.0.0"
dbt-core = "^1.1.1"
dbt-bigquery = "^1.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
